project:
  type: website

website:
  title: ""
  navbar:
    right:
      - icon: github
        href: https://github.com/
      - icon: mastodon
        href: https://fosstodon.org/@sarahaenzi
      - text: Main Website
        href: https://www.sarahaenzi.com/

format:
  html:
    theme: cosmo
    css: styles.css



