---
title: "Sleep Quality in Long Covid"
author: "Sara Hänzi"
date: "2024-09-16"
execute:
  echo: false
---

To start this long-covid blog, an indication of my sleep quality since covid: 

```{r}
library(ggplot2)
library(thematic)
library(tibble)

# prepare data
df <- tibble(category = c("Woke up tired", "Woke up refreshed"),
             values = c(100, 0))

sysfonts::font_add_google("Nunito")

# prepare theme

bs_theme_name <- "morph"
bs_theme_used <- bslib::bs_theme(bootswatch = bs_theme_name)
bs_vars <- c("primary", "secondary", "success", "info", "warning", "danger",
             "light", "dark")
bs_colors <- bslib::bs_get_variables(bs_theme_used, bs_vars)
thematic_rmd(bg = bs_colors[[2]],
             #fg = bs_colors[[2]],
             font = font_spec(families = "Nunito"))

# color for font: should probably be in the theme somewhere, in the css it is called
# bs-body-color
font_color <- "#7b8ab8" 
```


```{r}
# create plot
g <- df |>
  ggplot(aes(x = "", y = values, fill = category)) +
  geom_col() +
  scale_fill_manual(values = c("#bdc0fb", "#163865")) +
  # colors checked with aremycolorsaccessible.com, otherwise randomly chosen from bootstrap css
  coord_polar("y", start = 0) +
  theme(legend.key.size = unit(1.2, "cm"),
        axis.line = element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        plot.caption = element_text(size = 16, face = "plain"),
        legend.text = element_text(colour = font_color, size = 16),
        title = element_text(colour = font_color, face = "bold", size = 18),
        panel.background = element_rect(fill = bs_colors[[2]])
        ) +
  labs(title = "Sleep quality in Long Covid",
       fill = "",
       caption = "@sarahaenzi",
       alt = "Pie chart on sleep in long covid with 100% waking up tired and zero waking up refreshed.")
```

```{r}
#| fig-alt: !expr ggplot2::get_alt_text(g)
g
```


